version: '3'
services:
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile-laravel
    ports:
      - "8001:80"
    links:
      - "postgresql:postgresql"
    container_name: web
    volumes:
      - ./laravel:/var/www/laravel
      - ./apache-default.conf:/etc/apache2/sites-available/000-default.conf

volumes:
    postgres-data:
